test:
  solr:
    hostname: localhost
    port: <%= ENV['SOLR_REPLICA_PORT'] || 8980 %>
  auto_index_callback: after_commit
  auto_remove_callback: after_commit
development:
  solr:
    hostname: localhost
    port: 8981
config_test:
  solr:
    hostname: some.host
    port: <%= "1234".to_i %>
    path: /solr/idx
    log_level: WARNING
    data_path: /my_superior_path/data
    pid_dir: /my_superior_path/pids
    solr_home: /my_superior_path
    bind_address: 127.0.0.1
  auto_commit_after_request: false
  auto_commit_after_delete_request: true
  master:
    hostname: some.master_host
    port: 4321
    path: /master_solr/idx
    log_level: INFO
    data_path: /my_master_path/data
    pid_path: /my_master_path/pids
    solr_home: /my_master_path
config_disabled_test:
  disabled: true
config_commit_test:
  auto_index_callback: after_commit
  auto_remove_callback: after_commit
