test:
  solr:
    hostname: localhost
    port: <%= ENV['TEST_PORT'] || 8980 %>
development:
  solr:
    hostname: localhost
    port: 8981
config_test:
  solr:
    hostname: some.host
    port: 1234
    path: /solr/idx
    log_level: WARNING
    data_path: /my_superior99_path/data
    pid_path: /my_superior_path/pids
    solr_home: /my_superior_path
  auto_commit_after_request: false
  auto_commit_after_delete_request: true
  master:
    hostname: some.master_host
    port: 4321
    path: /master_solr/idx
    log_level: INFO
    data_path: /my_master_path/data
    pid_path: /my_master_path/pids
    solr_home: /my_master_path
